// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchStoreApi.Infrastructure.Persistence;

#nullable disable

namespace WatchStoreApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luxury"
                        });
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Stainless steel gents watch with a 38mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Doroly",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Stainless steel gents watch with a 38mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Aristos",
                            Price = 749.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Stainless steel gents watch with a 39mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Modicci",
                            Price = 849.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Automatic stainless steel watch for men with a 36mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Aurum",
                            Price = 949.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Stainless steel ladies watch with a 29mm dial in a luxury case.",
                            Gender = "Female",
                            Material = "Steel",
                            Name = "Aeri",
                            Price = 649.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Stainless steel ladies watch with a 21mm dial in a luxury case.",
                            Gender = "Female",
                            Material = "Steel",
                            Name = "Hope",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Stainless steel smart watch with a 21mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Torque Chain",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Smart watch with a 21mm dial and rubber straps.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Force Pro",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Unisex smart watch with a 21mm dial and rubber straps.",
                            Gender = "Unisex",
                            Material = "Steel",
                            Name = "Maxfit",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Feminine smart watch with a 21mm dial and rubber straps.",
                            Gender = "Female",
                            Material = "Steel",
                            Name = "Valentina",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Feminine smart watch with a 21mm dial and rubber straps.",
                            Gender = "Female",
                            Material = "Steel",
                            Name = "Ace",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Distinguished men's watch with a 46mm dial and a genuine leather strap in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Favous",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Sophisticated men's stainless steel watch with a 41mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Highlight",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Sophisticated stainless steel men's watch with a 39mm dial and dual time function.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Vanesio",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Robust stainless steel men's watch with a 41mm dial and dual time function.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Diesel",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Sophisticated men's gold watch with a 41mm dial in a titanium case.",
                            Gender = "Male",
                            Material = "Gold",
                            Name = "Spectrum",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Platinum men's watch with a 37mm dial and dual time function in a stainless steel case.",
                            Gender = "Male",
                            Material = "Platinum",
                            Name = "Wondrous",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "High-performance gold men's watch with a 34mm dial.",
                            Gender = "Male",
                            Material = "Gold",
                            Name = "Chrono",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Stainless steel men's watch with a 37mm dial in a luxury case.",
                            Gender = "Male",
                            Material = "Steel",
                            Name = "Ironman",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Bronze men's watch in a luxury case.",
                            Gender = "Male",
                            Material = "Bronze",
                            Name = "Royal",
                            Price = 599.99m
                        });
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Order", b =>
                {
                    b.HasOne("WatchStoreApi.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("WatchStoreApi.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchStoreApi.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("WatchStoreApi.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("WatchStoreApi.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("WatchStoreApi.Domain.Entities.Product", "Product")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchStoreApi.Domain.Entities.User", "User")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("WatchStoreApi.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
